---
title: "To estimate the growthform within a point frame"
author: "Tao Huang"
date: "9/13/2022"
output: html_document
---

# Load packages
```{r}
library("dplyr")
library("foreign")
```

# read the data
```{r}
pf<-read.csv("C:/Users/taohuang/Desktop/rcew-ltvr-point-frame-export/export.csv")
#pf<-read.csv("export.csv")
pf$growthform_ct<-1
pf$field_species_ct<-1
pf$Date<-as.POSIXct(pf$Date,format="%m/%d/%Y")
pf
```

# to find the highest litter area, I have to calculate litter fraction of site-date-plot-hit1.
```{r}
# the column i need
pf_field_species<-pf[,c("site","Date","plot","field_species","field_species_ct")]
pf_field_species

pf_count<- pf_field_species %>%    
  group_by(site,Date,plot,field_species ) %>%
   summarise(count=n())
pf_count

pf_count_l<-pf_count[pf_count$field_species %in% c("gl", "fl"),]

pf_count_l_wbs<-pf_count_l[ grepl("wbs", pf_count_l$site) ,]
pf_count_l_wbs
summary(pf_count_l_wbs)

pf_count_l_los<-pf_count_l[ grepl("los", pf_count_l$site) ,]
pf_count_l_los
summary(pf_count_l_los)

```


```{r}

lookup<-data.frame(field_species=c("sdw","ssdw","s","artrw8","drve2","gl","pose","w","pssp6","r","sl","m","fl","phlo2", "ascu5", "elel5", "andi2","brte", "2fa" ),description=c("shrub dead wood; >.25 inch or .5cm","standing shrub dead wood; >.25 inch or .5cm","soil; <.25 inch or .5cm","Wyoming big sagebrush","Draba verna L.","graminoid litter","pose","wood > .25 inch or .5cm","Bluebunch Wheatgrass","rock; >.25 inch or .5cm","shrub dead wood; <.25 inch or .5cm","moss","forb litter","Phlox longifolia", "Astragalus cusickii", "Elymus elymoides","Antennaria dimorpha", "Bromus tectorum", "Forb, annual"))
lookup

#https://plantsorig.sc.egov.usda.gov/java/charProfile?symbol=ARTRW8
#field_species
#d	dung
#POSE (small native bunchgrass)
#Poa bluegrass

```







# subset to WBS
```{r}
wbs<-pf[grepl("wbs", pf$site),]
table(wbs$site)
wbs$Date<- as.POSIXct(wbs$Date, format="%m/%d/%Y")
wbs
#save(wbs,file="wbs.Rdata")
```

# wbs plots include rock and moss
```{r}
wbs_r_m<-wbs[wbs$field_species %in% c("m","r"),]
dim(wbs_r_m)

wbs1<-wbs[wbs$site=="wbs1",]
wbs1_r_m<-wbs1[wbs1$field_species %in% c("m","r"),]
dim(wbs1_r_m)

wbs1<-wbs[wbs$site=="wbs1",]
wbs1_r_m_gl<-wbs1[wbs1$field_species %in% c("m","r","gl"),]
dim(wbs1_r_m_gl)
wbs1_r_m_gl[wbs1_r_m_gl$hit==1,]

wbs2<-wbs[wbs$site=="wbs2",]
wbs2_r_m<-wbs2[wbs2$field_species %in% c("m","r"),]
dim(wbs2_r_m)

wbs3<-wbs[wbs$site=="wbs3",]
wbs3_r_m<-wbs3[wbs3$field_species %in% c("m","r"),]
dim(wbs3_r_m)
```


# count field_species of wbs 1 (and 2)
```{r}

for (i in c(1:2)) {
   print(i)
}

wbs1_field_species<-wbs1[,c("site","Date","plot","field_species","field_species_ct")]

wbs1_count<-wbs1_field_species %>%    
  group_by(site,Date,plot,field_species) %>%
   summarise(count=n())

wbs1_plot<-wbs1_field_species %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

wbs1_all<-merge(wbs1_count,wbs1_plot,by=c("site","Date","plot") )
wbs1_all$fraction<-wbs1_all$count/wbs1_all$total_count
wbs1_all

```


<!-- # count field_species of wbs 1 (hit==1) -->
<!-- ```{r} -->



<!-- wbs1_field_species<-wbs1[ wbs1$hit==1 ,c("site","Date","plot","field_species","field_species_ct")] -->

<!-- wbs1_count<-wbs1_field_species %>%     -->
<!--   group_by(site,Date,plot,field_species) %>% -->
<!--    summarise(count=n()) -->

<!-- wbs1_plot<-wbs1_field_species %>%     -->
<!--   group_by(site,Date,plot) %>% -->
<!--    summarise(total_count=n()) -->

<!-- wbs1_all<-merge(wbs1_count,wbs1_plot,by=c("site","Date","plot") ) -->
<!-- wbs1_all$fraction<-wbs1_all$count/wbs1_all$total_count -->
<!-- wbs1_all -->
<!-- wbs1_all[wbs1_all$fraction>0.1,] -->
<!-- ``` -->


# wbs1_all
```{r}
wbs1_all_2019<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y"),]
wbs1_all_2019[wbs1_all_2019$field_species=="m",]
wbs1_all_2019[wbs1_all_2019$field_species=="pose",]
#drve2
wbs1_all_2019[wbs1_all_2019$field_species=="drve2",]
#gl
wbs1_all_2019[wbs1_all_2019$field_species=="gl",]
wbs1_all_2019_plot12<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs1_all$plot==12,]
wbs1_all_2019_plot12
wbs1_all_2019_plot18<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs1_all$plot==18,]
wbs1_all_2019_plot18
wbs1_all_2019_plot19<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs1_all$plot==19,]
wbs1_all_2019_plot19
wbs1_all_2019_plot22<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs1_all$plot==22,]
wbs1_all_2019_plot22
#wbs1_all_2019_plot23<-wbs3_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs3_all$plot==23,]
#wbs1_all_2019_plot23
wbs1_all_2019_plot31<-wbs1_all[wbs1_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs1_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs1_all$plot==31,]
wbs1_all_2019_plot31
#wbs1_all_2019_plot15<-wbs1_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs3_all$plot==15,]
#wbs1_all_2019_plot15
```

```{r}
wbs1_all_2019[wbs1_all_2019$count>26,]
```



```{r}
wbs1_all_2019_plot12_sp<-merge(wbs1_all_2019_plot12,lookup,by.x="field_species",by.y="field_species")
wbs1_all_2019_plot12_sp
```


```{r}
rhem_lookup<-data.frame( field_species =c("artrw8","elel5","gl","m","phlo2",   "pose", "s","sl", "ssdw", "drve2", "ascu5", "r", "sdw", "andi2", "brte", "pssp6"),RHEM=c("Shrubs","Bunch Grass","Litter Cover %","Biological Crusts Cover","Forbs/Annuals", "Bunch Grass", "Bare", "Shrubs" , "Shrubs", "Forbs/Annuals", "Forbs/Annuals", "rock", "Shrubs", "Forbs/Annuals", "Forbs/Annuals", "Bunch Grass"))
rhem_lookup
```


```{r}
wbs1_all_2019_plot12_sp_rhem<-merge( wbs1_all_2019_plot12_sp,rhem_lookup,by.x="field_species",by.y="field_species")
wbs1_all_2019_plot12_sp_rhem
sum(wbs1_all_2019_plot12_sp_rhem$fraction)
```


```{r}
Shrubs<-sum(wbs1_all_2019_plot12_sp_rhem[wbs1_all_2019_plot12_sp_rhem$RHEM=="Shrubs",]$fraction)
Shrubs

Forbs <-sum(wbs1_all_2019_plot12_sp_rhem[wbs1_all_2019_plot12_sp_rhem$RHEM=="Forbs/Annuals",]$fraction)
Forbs

Bunch  <-sum(wbs1_all_2019_plot12_sp_rhem[wbs1_all_2019_plot12_sp_rhem$RHEM=="Bunch Grass",]$fraction)
Bunch

crust  <-sum(wbs1_all_2019_plot12_sp_rhem[wbs1_all_2019_plot12_sp_rhem$RHEM=="Biological Crusts Cover",]$fraction)
crust

Bare <-sum(wbs1_all_2019_plot12_sp_rhem[wbs1_all_2019_plot12_sp_rhem$RHEM=="Bare",]$fraction)
Bare

```

```{r}
wbs1_all_sp<-data.frame(table(wbs1_all$field_species))
colnames(wbs1_all_sp)<-c("field_species","freq")
wbs1_all_sp
wbs1_all_sp_rhem<-merge( wbs1_all_sp,rhem_lookup,by.x="field_species",by.y="field_species")
wbs1_all_sp_rhem

wbs1_all_sp_rhem_group<-  wbs1_all_sp_rhem %>% group_by(RHEM) %>% summarise(sum=sum(freq))
wbs1_all_sp_rhem_group

```











# wbs3_all

# count field_species of wbs 3
```{r}
wbs3_field_species<-wbs3[,c("site","Date","plot","field_species","field_species_ct")]

wbs3_count<-wbs3_field_species %>%    
  group_by(site,Date,plot,field_species) %>%
   summarise(count=n())

wbs3_plot<-wbs3_field_species %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

wbs3_all<-merge(wbs3_count,wbs3_plot,by=c("site","Date","plot") )
wbs3_all$fraction<-wbs3_all$count/wbs3_all$total_count
wbs3_all
#pf %>% group_by(site) %>%tally()
```

# wbs3_all
```{r}
wbs3_all_2019<-wbs3_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y"),]
wbs3_all_2019[wbs3_all_2019$field_species=="m",]
wbs3_all_2019_plot23<-wbs3_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs3_all$plot==23,]
wbs3_all_2019_plot23
wbs3_all_2019_plot31<-wbs3_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs3_all$plot==31,]
wbs3_all_2019_plot31
wbs3_all_2019_plot15<-wbs3_all[wbs3_all$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & wbs3_all$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs3_all$plot==15,]
wbs3_all_2019_plot15
```


```{r}
wbs3_all_2019_plot15_sp<-merge( wbs3_all_2019_plot15,lookup,by.x="field_species",by.y="field_species")
wbs3_all_2019_plot15_sp
```

```{r}
wbs3_all_2019_plot15_sp_rhem<-merge( wbs3_all_2019_plot15_sp,rhem_lookup,by.x="field_species",by.y="field_species")
wbs3_all_2019_plot15_sp_rhem
```













# Subset to wbs1 2019 plot 10
```{r}
pf_wbs1_2019_plot10<-pf[pf$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & pf$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & pf$site=="wbs1" & pf$plot==10,]
pf_wbs1_2019_plot10
pf_wbs1_2019_plot10[pf_wbs1_2019_plot10$row==5,]
table(pf_wbs1_2019_plot10$hit)
table(pf_wbs1_2019_plot10$growthform)
write.csv(pf_wbs1_2019_plot10[pf_wbs1_2019_plot10$hit==1,],file="pf_wbs1_2019_plot10_hit1.csv")
```

# Subset to wbs1 2016 plot 10
```{r}
pf_wbs1_2016_plot10<-pf[pf$Date>=as.POSIXct("01/01/2016",format="%m/%d/%Y") & pf$Date<as.POSIXct("01/01/2017",format="%m/%d/%Y") & pf$site=="wbs1" & pf$plot==10,]
pf_wbs1_2016_plot10
pf_wbs1_2016_plot10[pf_wbs1_2016_plot10$row==1,]
table(pf_wbs1_2016_plot10$hit)
table(pf_wbs1_2016_plot10$growthform)
```

# Subset to wbs1 2018 plot 10
```{r}
pf_wbs1_2018_plot10<-pf[pf$Date>=as.POSIXct("01/01/2018",format="%m/%d/%Y") & pf$Date<as.POSIXct("01/01/2019",format="%m/%d/%Y") & pf$site=="wbs1" & pf$plot==10,]
pf_wbs1_2018_plot10
pf_wbs1_2018_plot10[pf_wbs1_2018_plot10$row==1,]
table(pf_wbs1_2018_plot10$hit)
table(pf_wbs1_2018_plot10$growthform)

```


# count field_species
```{r}
pf_field_species<-pf[,c("site","Date","plot","field_species","field_species_ct")]

pf_count<-pf_field_species %>%    
  group_by(site,Date,plot,field_species) %>%
   summarise(count=n())

pf_plot<-pf_field_species %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

pf_all<-merge(pf_count,pf_plot,by=c("site","Date","plot") )
pf_all$fraction<-pf_all$count/pf_all$total_count
pf_all
#pf %>% group_by(site) %>%tally()
```

# count growthform
```{r}
pf<-pf[,c("site","Date","plot","growthform","growthform_ct")]

pf_count<-pf %>%    
  group_by(site,Date,plot,growthform) %>%
   summarise(count=n())

pf_plot<-pf %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

pf_all<-merge(pf_count,pf_plot,by=c("site","Date","plot") )
pf_all$fraction<-pf_all$count/pf_all$total_count
pf_all
#pf %>% group_by(site) %>%tally()
```

```{r}
rtk<-read.dbf("/Users/owner/Downloads/LTVR_LAI_RTK-corrected/LTVM_PointFrame_wDirection.dbf")
rtk_wbsveg1<-rtk[rtk$NWRC_Ref=="wbsveg1",]
rtk_wbsveg1
```

