---
title: "Untitled"
author: "Tao Huang"
date: "9/13/2022"
output: html_document
---

```{r}
library("dplyr")
library("foreign")
```

```{r}
pf<-read.csv("C:/Users/taohuang/Desktop/rcew-ltvr-point-frame-export/export.csv")
pf$growthform_ct<-1
pf$field_species_ct<-1
pf$Date<-as.POSIXct(pf$Date,format="%m/%d/%Y")
```

```{r}
pf_wbs1_2019_plot10<-pf[pf$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") & pf$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & pf$site=="wbs1" & pf$plot==10,]
pf_wbs1_2019_plot10
pf_wbs1_2019_plot10[pf_wbs1_2019_plot10$row==1,]
```

field_species
```{r}
pf<-pf[,c("site","Date","plot","field_species","field_species_ct")]

pf_count<-pf %>%    
  group_by(site,Date,plot,field_species) %>%
   summarise(count=n())

pf_plot<-pf %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

pf_all<-merge(pf_count,pf_plot,by=c("site","Date","plot") )
pf_all$fraction<-pf_all$count/pf_all$total_count
pf_all
#pf %>% group_by(site) %>%tally()
```


growthform
```{r}
pf<-pf[,c("site","Date","plot","growthform","growthform_ct")]

pf_count<-pf %>%    
  group_by(site,Date,plot,growthform) %>%
   summarise(count=n())

pf_plot<-pf %>%    
  group_by(site,Date,plot) %>%
   summarise(total_count=n())

pf_all<-merge(pf_count,pf_plot,by=c("site","Date","plot") )
pf_all$fraction<-pf_all$count/pf_all$total_count
pf_all
#pf %>% group_by(site) %>%tally()
```

```{r}
wbs<-pf_all[grepl("wbs", pf_all$site),]
table(wbs$site)
wbs$Date<- as.POSIXct(wbs$Date, format="%m/%d/%Y")
wbs
#save(wbs,file="wbs.Rdata")
```

```{r}
wbs1_2019_plot10<-wbs[wbs$Date>=as.POSIXct("01/01/2019",format="%m/%d/%Y") &wbs$Date<as.POSIXct("01/01/2021",format="%m/%d/%Y") & wbs$site=="wbs1" &wbs$plot==10,]
wbs1_2019_plot10

lookup<-data.frame(field_species=c("sdw","ssdw","s","artrw8","drve2","gl","pose","w","pssp6","r","sl"),description=c("shrub dead wood; >.25 inch or .5cm","standing shrub dead wood; >.25 inch or .5cm","soil; <.25 inch or .5cm","artrw8","drve2","graminoid litter","pose","wood > .25 inch or .5cm","pssp6","rock; >.25 inch or .5cm","shrub dead wood; <.25 inch or .5cm"))
lookup

#field_species
#fl	forb litter
#m	moss
#d	dung

#POSE (small native bunchgrass)
#Poa bluegrass

wbs1_2019_plot10_sp<-merge(wbs1_2019_plot10,lookup,by.x="field_species",by.y="field_species")
wbs1_2019_plot10_sp
```

```{r}
rtk<-read.dbf("/Users/owner/Downloads/LTVR_LAI_RTK-corrected/LTVM_PointFrame_wDirection.dbf")
rtk_wbsveg1<-rtk[rtk$NWRC_Ref=="wbsveg1",]
rtk_wbsveg1
```

